#!/usr/bin/env python3

import sy
import numpy as np

groups = [line for line in sys.stdin.read().split("\n\n")]
groups = [group.rstrip().split("\n") for group in groups]

sums = [np.sum([int(e) for e in group]) for group in groups]
print(np.max(sums))
