#!/usr/bin/env python3

import sys

groups = [line for line in sys.stdin.read().split("\n\n")]
groups = [group.rstrip().split("\n") for group in groups]

print(max([sum([int(e) for e in group]) for group in groups]))
