#!/bin/bash

DAY=$(date +%-d)

curl "https://adventofcode.com/2022/day/$DAY/input" \
	-H 'User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:107.0) Gecko/20100101 Firefox/107.0' \
	-H 'Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,*/*;q=0.8' \
	-H 'Accept-Language: en-US,en;q=0.5' \
	-H 'Accept-Encoding: gzip, deflate, br' \
	-H "Referer: https://adventofcode.com/2022/day/$DAY" \
	-H 'Connection: keep-alive' \
	#XXX Add your own session ID below XXX
	-H 'Cookie: session=<session id>' \
	-H 'Upgrade-Insecure-Requests: 1' \
	-H 'Sec-Fetch-Dest: document' \
	-H 'Sec-Fetch-Mode: navigate' \
	-H 'Sec-Fetch-Site: same-origin' \
	-H 'Sec-Fetch-User: ?1' | gunzip > day$DAY/input
