#!/usr/bin/env python3

import sys

input = sys.stdin.read().rstrip()
orig = [(int(line), i) for i, line in enumerate(input.split("\n"))]
state = [e for e in orig]

length = len(orig)

for e in orig:
    offset, id = e

    cur_i = state.index(e)
    new_i = (cur_i + offset) % (length-1)

    if offset == 0:
        continue

    state.remove(e)
    state.insert(new_i, (offset, id))

nums = [s[0] for s in state]

print(sum([nums[(o+nums.index(0))%length] for o in [1000, 2000, 3000]]))
