#!/usr/bin/env python3


ans = 0

while 1:
    try:
        x = input()
        xs = x.split(",")

        r1 = xs[0].split("-")
        r2 = xs[1].split("-")

        r1 = [*range(int(r1[0]), int(r1[1]) + 1)]
        r2 = [*range(int(r2[0]), int(r2[1]) + 1)]

        contained = False

        for r in r1:
            contained = True
            if r not in r2:
                contained = False
                break

        ans += contained

        if contained:
            continue

        for r in r2:
            contained = True
            if r not in r1:
                contained = False
                break

        ans += contained

    except EOFError:
        break

print(ans)
