#!/usr/bin/env python3

ans = 0

while 1:
    try:
        x = input()
        xs = x.split(",")

        r1 = xs[0].split("-")
        r2 = xs[1].split("-")

        r1 = [*range(int(r1[0]), int(r1[1]) + 1)]
        r2 = [*range(int(r2[0]), int(r2[1]) + 1)]

        for r in r1:
            if r in r2:
                ans += 1
                break

    except EOFError:
        break

print(ans)
