#!/usr/bin/env python3

import sys

input = sys.stdin.read().rstrip()
lines = [line for line in input.split("\n")]

dict = {}

for line in lines:
    key, val = line.split(": ")
    dict[key] = int(val) if val.isnumeric() else val

def solve(key):
    if isinstance(dict[key], int):
        return dict[key]

    val = dict[key]

    if val.find("/") > -1:
        a, b = val.split(" / ")
        return solve(a) // solve(b)
    if val.find("*") > -1:
        a, b = val.split(" * ")
        return solve(a) * solve(b)
    if val.find("+") > -1:
        a, b = val.split(" + ")
        return solve(a) + solve(b)
    if val.find("-") > -1:
        a, b = val.split(" - ")
        return solve(a) - solve(b)

    assert 0

print(solve("root"))
