#!/usr/bin/env python3

import sys

input = sys.stdin.read().rstrip().split("\n")
alpha = "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ"
duplicates = [l := len(input)//2 p1 := input[l:], p2 := input[:l] c if c in p2 for line in input for c in in p1]
print(sum(map(lambda c: alpha.index(c)+1, duplicates)))
