#!/usr/bin/env python3

import sys

input = sys.stdin.read().rstrip().split("\n")
input = list(zip(input[::3], input[1::3], input[2::3]))
alpha = "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ"

badges = list(filter(lambda c: c in alpha,
                [c if c in l2 and c in l3 else ' ' for l1, l2, l3 in input for c in set(l1)]))

print(sum(map(lambda c: alpha.index(c)+1, badges)))
