#!/usr/bin/env python3

import sys
import numpy as np

class Monkey:
    pass

monkeys = []

input = [monkey for monkey in sys.stdin.read().rstrip().split("\n\n")]

for monkey in input:
    line = monkey.rstrip().split("\n")
    m = Monkey()
    m.items = [int(i) for i in line[1].split(":")[1].split(",")]
    m.op = line[2].split(":")[1].split("=")[1].strip()
    m.test = int(line[3].split(":")[1].strip().split(" ")[2])
    m.true = int(line[4].split(":")[1].strip().split(" ")[3])
    m.false = int(line[5].split(":")[1].strip().split(" ")[3])
    m.thrown = 0

    monkeys.append(m)

mod = np.product([m.test for m in monkeys])

for i in range(10000):
    for m in monkeys:
        m.thrown += len(m.items)
        for item in m.items:
            old = item
            worry = eval(m.op)

            worry %= mod

            if worry % m.test == 0:
                monkeys[m.true].items.append(worry)
            else:
                monkeys[m.false].items.append(worry)

        m.items = []

active = [m.thrown for m in monkeys]
active.sort(reverse=1)

print(active[0] * active[1])
