#!/usr/bin/env python3

ans = 0

accum = 1
clock = 0

check = 20

screen = []

while 1:
    try:
        x = input()
        xs = x.split(" ")

        opcode = xs[0]

        cycle = 0

        sprite = []
        for i in range(40):
            if abs(accum - i) <= 1:
                sprite.append("#")
            else:
                sprite.append(".")

        if opcode == "noop":
            cycle = 1
            arg = 0
        elif opcode == "addx":
            arg = int(xs[1])
            cycle = 2

        while cycle > 0:
            i = clock % 40
            if sprite[i] == "#":
                screen.append("#")
            else:
                screen.append(".")

            cycle -= 1
            clock += 1

        accum += arg


    except EOFError:
        break

print(clock)

for i, c in enumerate(screen):
    if i % 40 == 0:
        print()
    else:
        print(c, end="")
print()
