#!/usr/bin/env python3

dir = []
path = ""
tree = {}

while 1:
    try:
        x = input()
        x = x.split(" ")

        if x[0] == "$":
            command= x[1]
            if command == "cd":
                arg = x[2]

                if arg == "..":
                    dir.pop()
                else:
                    dir.append(arg)

                oldpath = path
                path = ".".join(dir)

                if tree.get(path) == None:
                    tree[path] = {
                            "contains": [],
                            "size": 0
                            }
        elif x[0] != "dir":
            tree[path]["size"] += int(x[0])
        else:
            name = x[1]
            tree[path]["contains"].append(path + "." + name)
    except EOFError:
        break

def total(path):
    node = tree[path]
    sum = node["size"]

    for p in node["contains"]:
        sum += total(p)

    return sum


print(total("/"))

ans = 0
for path in tree:
    node = tree[path]
    size = total(path)

    ans += size if size <= 100000 else 0

print(ans)
