#!/usr/bin/env python3

import sys

(start, input) = tuple(sys.stdin.read().rstrip().split("\n\n"))

start = start.split("\n")

stack = []

for i in range(0, len(start[0]), 4):
    stack.append([])
    for line in start:
        box = line[i:i+4].strip()

        if "[" in box and "]" in box:
            stack[-1].append(box.strip("[]"))

for i in range(len(stack)):
    stack[i].reverse()

input = input.rstrip().split("\n")

for line in input:
    part = line.split(" ")
    count = int(part[1])
    fr = int(part[3]) - 1
    to = int(part[5]) - 1

    while count > 0:
        crate = stack[fr].pop()
        stack[to].append(crate)
        count -= 1

for e in stack:
    print(e[-1], end="")

print()
