#!/usr/bin/env python3

ans = 0

map = []
vis = []

while 1:
    try:
        x = input()
        map.append(x)
        vis.append([])

        for c in x:
            vis[-1].append(0)

    except EOFError:
        break

for y in range(len(map)):
    max = -1
    for x in range(len(map[y])):
        h = int(map[y][x])
        if h > max:
            vis[y][x] = 1
            max = h

for y in range(len(map)):
    max = -1
    for x in range(len(map[y]) - 1, -1, -1):
        h = int(map[y][x])
        if h > max:
            vis[y][x] = 1
            max = h

for x in range(len(map[0])):
    max = -1
    for y in range(len(map)):
        h = int(map[y][x])
        if h > max:
            vis[y][x] = 1
            max = h

for x in range(len(map[0])):
    max = -1
    for y in range(len(map) - 1, -1, -1):
        h = int(map[y][x])
        if h > max:
            vis[y][x] = 1
            max = h

for row in vis:
    for x in row:
        if x:
            ans += 1

print(ans)
