#!/usr/bin/env python3

ans = 0

map = []

while 1:
    try:
        x = input()
        map.append(x)

    except EOFError:
        break

delta = [
        (0, 1),
        (0, -1),
        (-1, 0),
        (1, 0),
        ]

lim = (len(map[0]), len(map))

for y in range(1, len(map) - 1):
    for x in range(1, len(map[y]) - 1):
        s = []
        h = int(map[y][x])
        for d in delta:
            s.append(0)
            (dx, dy) = d
            (lx, ly) = lim
            (x0, y0) = (x+dx, y+dy)
            while(x0 >= 0 and y0 >= 0 and x0 < lx and y0 < ly):
                s[-1] += 1
                if int(map[y0][x0]) >= h:
                    break

                x0 += dx
                y0 += dy

        score = s[0] * s[1] * s[2] * s[3]
        if score > ans:
            ans = score

print(ans)
