#!/usr/bin/env python3

import sys

grid = [list(line) for line in sys.stdin.read().rstrip().split("\n")]

start = ()

for y in range(len(grid)):
    for x in range(len(grid[y])):
        c = grid[y][x]
        if c == "E":
            start = (x, y)
            grid[y][x] = "z"

queue = [[start]]
visited = []
depth = 0

(w, h) = (len(grid[0]), len(grid))

while queue:
    batch = queue.pop(0)

    next_batch = []
    for node in batch:
        (x, y) = node
        if grid[y][x] == "a":
            print(depth)
            exit()

        for dx, dy in [(0, 1), (0, -1), (1, 0), (-1, 0)]:
            (x, y) = node

            v = ord(grid[y][x])
            x += dx
            y += dy

            if x >= w or x < 0:
                continue
            if y >= h or y < 0:
                continue

            nv = ord(grid[y][x])

            if v - nv <= 1 and (x, y) not in visited:
                next_batch.append((x, y))
                visited.append((x, y))

    queue.append(next_batch)
    depth += 1
